# =====================================================================
# Sink: SNS Client
# =====================================================================
debezium.sink.type=sns
debezium.sink.sns.region=us-east-1
debezium.sink.sns.endpoint=http://localstack:4566

# Tópico SNS para onde os eventos serão publicados FIXO
#debezium.sink.sns.topic.arn=arn:aws:sns:us-east-1:000000000000:sqlserver_cdc-dbo-pessoa
##aws = partição (na AWS “normal”)
##sns = serviço
##us-east-1 = região
##000000000000 = account id (no LocalStack costuma ser esse “fake”)
##cdcserver.dbo.pessoa = nome do tópico (recurso)

# Em AWS real, use o seu accountId (nÃ£o 000000000000)
debezium.sink.sns.topic.arn.prefix=arn:aws:sns:us-east-1:000000000000:

# Força o Debezium a usar as credenciais estáticas do LocalStack sem validar tokens reais da AWS
quarkus.sns.endpoint-override=http://localstack:4566
quarkus.sns.aws.region=us-east-1
quarkus.sns.aws.credentials.type=static
quarkus.sns.aws.credentials.static-provider.access-key-id=test
quarkus.sns.aws.credentials.static-provider.secret-access-key=test

# =====================================================================
# SOURCE: SQL Server (via CDC nativo)
# =====================================================================
debezium.source.connector.class=io.debezium.connector.sqlserver.SqlServerConnector
debezium.source.database.hostname=sqlserver
debezium.source.database.port=1433
debezium.source.database.user=sa
debezium.source.database.names=cadastrodb
debezium.source.database.password=YourStrong!Passw0rd
debezium.source.database.encrypt=false
debezium.source.database.trustServerCertificate=true


# Prefixo usado na geração do nome do tópico: <prefix>.<schema>.<tabela>
# Ex.: cdcserver.dbo.pessoa  -> precisa bater com o tópico criado no pubsub-init
debezium.source.topic.prefix=cdcserver

debezium.source.topic.delimiter=-

# Somente a tabela pessoa
debezium.source.table.include.list=dbo.pessoa

# Histórico de schema e offsets em arquivo (sem necessidade de Kafka)
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/dbhistory.dat
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=0

# =====================================================================
# Logs
# =====================================================================
quarkus.log.level=INFO
quarkus.log.console.json=false
debezium.format.value=json
